### ISSUE TITLE
Is it acceptable to use --download-foo in the recipe?

### ISSUE THREAD

**Issue by garth-wells** [conda-forge/petsc-feedstock#11]
Is it ok to use `--download-foo` in the recipe?

A problem is that some optional dependencies are not available as conda packages, and some packages that are available have dependency conflicts (primarily MPI).

Moreover, some package are not well maintained, and using `--download-foo` increases the likelihood of having compatible versions.

**Comment by dalcinl** [comment]
@garth-wells In general, your request in against the conda-forge general guidelines. Moreover, MUMPS is already a package, so we have to fix the mess. Moreover, I think the MPI-dep issues are rather trivial to fix, see my comments here https://github.com/conda-forge/staged-recipes/pull/1501.

@minrk We have to take a decision on this MPI mess we currently have, use conda features the right way, and build MPI-based packages for both MPICH and Open MPI.

**Comment by garth-wells** [comment]
On a philosophical note, I'm unconvinced that any package manager will ever be able adequately handle optional dependencies - it gets too complicated. Looking at the MUMPS package, there are issues around not only MPI but also SCOTCH vs PT-SCOTCH.

**Comment by minrk** [comment]
Which packages would you like to add?

I'd like to avoid `--download` where possible, at least. Especially for packages with a different license than PETSc, since that complicates things once they are bundled together.

I've looked at PETSc's bundling, and in each case I've encountered so far, making a proper package and normal dependency hasn't been an issue. I build the scotch package based on PETSc's build, for instance.

@dalcinl I agree that the MPI case is easy, I'd just like an official position on https://github.com/conda-forge/staged-recipes/pull/1501 before deploying it. I opened PRs implementing the latest proposal, so that propagating should be easy once it's decided.

**Comment by garth-wells** [comment]
MUMPS - see #12.
